repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
        - id: trailing-whitespace
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-case-conflict
        - id: check-toml
        - id: check-merge-conflict
        - id: check-xml
        - id: check-yaml
        - id: end-of-file-fixer
        - id: check-symlinks
        - id: mixed-line-ending
        - id: pretty-format-json
          args: [--autofix]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
        - id: flake8
          args:
            - --ignore=E203,E402,E501,E800,W503,W391,E261
            - --select=B,C,E,F,W,T4,B9

  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
        - id: black
          args: [--safe]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
        - id: mypy
          additional_dependencies: [Flask==2.0.1, types-cachetools==0.1.6, types-requests==0.1.10]
