version: "3"

services:
    app:
        build: .
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: 1
        command: flask run --host=0.0.0.0 --port 3030
        volumes:
            - ./src:/app
