version: "3"

services:
    app:
        restart: always
        build: .
        environment:
            FLASK_APP: app
            FLASK_ENV: production
        command: gunicorn --workers=2 --bind 0.0.0.0:3030 app:app
        ports:
            - "3030:3030"