name: Lint and Test

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        # need to install all dependencies for mypy so that we have all the type stubs
        run: pip install -r requirements-dev.txt
      - name: Run pre-commit checks
        run: pre-commit run --all-files

  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Build image
        run: just build
      - name: Start server
        run: just up
      - name: Check server
        run: |
          # Wait for the server to be ready
          sleep 5
          curl --fail -LI localhost:3030 -o /dev/null -w '%{http_code}\n'
      - name: Stop server
        if: always()
        run: just down
