name: Lint and Test

on: pull_request

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install black
      - name: Check formatting with black
        run: black --check --line-length=150 --safe .

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install flake8
      - name: Lint with flake8
        run: flake8 .

  types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        # need to install all dependencies for mypy so that we have all the type stubs
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Check typing with mypy
        run: mypy .
